# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Homework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Homework
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Alamofire'
  pod 'RxReachability'
  pod 'RxAlamofire'
  pod 'SwiftyJSON'
  pod 'DropDown'

  target 'HomeworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HomeworkUITests' do
    # Pods for testing
  end

end
